### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Sungray** [Karry/TimeLapse#8]
Hi, sorry for probably stupid question, but I don't understand how to run this.
Could you provide a simple example? Setup is OK, no worries there, but IDK what to do after this.
Thanks!

**Comment by Karry** [comment]
Hi. These tools are just command line, not UI. So you need to execute them from some terminal. Examples are on wiki: https://github.com/Karry/TimeLapse/wiki/

**Comment by Sungray** [comment]
Thanks! Must've missed it, very clear.
